import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { entityId } from '../platform/ids';
import { buildAgentPrompt } from './prompt';
import {
  generateBranchName,
  createReviewBranch,
  changedFiles,
  commitAll,
  restoreBranch,
} from './git/repo';
import { verifyRepository } from './git/verify';
import { assertSafeChangedFiles } from './git/change-policy';
import { openDraftPullRequest } from './pull-request';
import type { AgentResult, CodingAgent } from './types';
import type { Repositories } from '../feedback/storage/repositories';
import type {
  AgentJob,
  JobStatus,
  Project,
  RepositoryInfo,
  SubmittedReview,
  VerificationResult,
} from '../app/types';

export interface OrchestratorDeps {
  repositories: Repositories;
  agent: CodingAgent;
  /** Directory for sanitized per-job agent logs. */
  logsDir?: string;
  /** Called on every persisted status change (including the initial queue). */
  onStatus?: (job: AgentJob) => void;
}

const TERMINAL: JobStatus[] = ['pr-opened', 'failed'];

function isActive(job: AgentJob): boolean {
  return !TERMINAL.includes(job.status);
}

/** Build a RepositoryInfo view from a project (used for verification gates). */
function infoForProject(project: Project, worktreePath: string, baseCommit: string): RepositoryInfo {
  // Verification runs ONLY the build gate (speed choice): it's the cheap, high
  // signal "does it still build/compile" check. The slower test/lint/typecheck
  // gates are dropped — the draft PR is human-reviewed (and GitHub CI can run
  // the full suite). Install is skipped too: the developer's repo already has
  // node_modules, and `npm ci` would wipe and reinstall it.
  const commands: RepositoryInfo['commands'] = project.commands.build
    ? { build: project.commands.build }
    : {};
  return {
    root: worktreePath,
    clean: true,
    branch: project.baseBranch,
    commit: baseCommit,
    githubRepo: project.githubRepo,
    framework: project.framework,
    htmlEntry: project.htmlEntry,
    commands,
  };
}

/** Verification commands (arg arrays) surfaced to the agent — build only. */
function verificationCommands(project: Project): string[][] {
  const build = project.commands.build;
  return build ? [[build.command, ...build.args]] : [];
}

function prBody(review: SubmittedReview, changed: string[], verification: VerificationResult): string {
  const lines: string[] = [];
  lines.push(`## Visual feedback from ${review.reviewerName}`);
  lines.push('');
  lines.push(`Generated by Pinpoint from review \`${review.id}\` (base \`${review.baseCommit}\`).`);
  lines.push('');
  lines.push('### Feedback applied');
  review.annotations.forEach((a) => {
    const src = a.mapping.sourceFile ?? a.mapping.component ?? 'unresolved';
    lines.push(`${a.index}. **<${a.tag}>** — ${a.comment}  \n   _source: ${src}_`);
  });
  lines.push('');
  lines.push('### Files changed');
  changed.forEach((f) => lines.push(`- \`${f}\``));
  lines.push('');
  lines.push('### Verification');
  verification.checks
    .filter((c) => !c.skipped)
    .forEach((c) => lines.push(`- ${c.ok ? '✅' : '❌'} \`${c.command.join(' ')}\``));
  lines.push('');
  lines.push('---');
  lines.push('> Draft opened automatically. Review before merging. Pinpoint never merges or force-pushes.');
  return lines.join('\n');
}

/** Hard bound on a single agent run so a hung/looping agent can't stall forever. */
const AGENT_TIMEOUT_MS = 240_000;

/** Turn a failed agent result into a concise, useful reason for the dashboard/logs. */
function agentFailureDetail(result: AgentResult): string {
  if (result.timedOut) return 'the coding agent timed out';
  if (result.aborted) return 'the coding agent was cancelled';
  const events = result.events ?? [];
  const rateLimited = events.some(
    (e) => e.type === 'rate_limit_event' || (typeof e.subtype === 'string' && e.subtype.includes('rate')),
  );
  const resultEvent = [...events].reverse().find((e) => e.type === 'result') as
    | { is_error?: boolean; subtype?: string; result?: unknown }
    | undefined;
  if (resultEvent?.is_error) {
    const r = resultEvent.result;
    return typeof r === 'string' && r.trim()
      ? r.trim().slice(0, 300)
      : resultEvent.subtype ?? 'the coding agent reported an error';
  }
  if (!resultEvent) {
    return rateLimited
      ? 'Claude hit API rate limits before finishing — wait a bit and retry'
      : 'the coding agent ended without completing (no result event)';
  }
  return 'the coding agent did not complete successfully';
}

/** A job failure carrying a human-readable reason for the dashboard. */
class JobError extends Error { }

/**
 * Persisted job state machine:
 *   queued → preparing → running-agent → verifying → pushing → pr-opened
 *                                                        ↘ failed (any stage)
 * State is persisted before and after every external operation so an
 * interrupted run can be recovered rather than silently rerun.
 */
export class Orchestrator {
  private readonly running = new Map<string, Promise<void>>();

  constructor(private readonly deps: OrchestratorDeps) { }

  async getJob(jobId: string): Promise<AgentJob | undefined> {
    return this.deps.repositories.jobs.get(jobId);
  }

  /** Await a started job's pipeline (test/shutdown helper). */
  async settle(jobId: string): Promise<void> {
    await this.running.get(jobId);
  }

  /** Await all in-flight pipelines. */
  async settleAll(): Promise<void> {
    await Promise.all([...this.running.values()]);
  }

  async startJobForReview(reviewId: string): Promise<AgentJob> {
    const review = await this.deps.repositories.reviews.get(reviewId);
    if (!review) throw new Error(`unknown review: ${reviewId}`);
    const project = await this.deps.repositories.projects.get(review.projectId);
    if (!project) throw new Error(`unknown project for review: ${reviewId}`);

    const all = await this.deps.repositories.jobs.list();
    const forReview = all.filter((j) => j.reviewId === reviewId);
    if (forReview.some(isActive)) {
      throw new Error('a job is already active for this review');
    }

    const now = new Date().toISOString();
    const job: AgentJob = {
      id: entityId('job'),
      reviewId,
      projectId: project.id,
      status: 'queued',
      attempts: forReview.length + 1,
      createdAt: now,
      updatedAt: now,
    };
    await this.deps.repositories.jobs.insert(job);
    this.deps.onStatus?.(job);

    const p = this.runPipeline(job.id, review, project).catch(async (err) => {
      await this.fail(job.id, err instanceof Error ? err.message : String(err));
    });
    this.running.set(job.id, p);
    return job;
  }

  /** Mark interrupted nonterminal jobs failed (recoverable) after a restart. */
  async recoverInterrupted(): Promise<number> {
    const all = await this.deps.repositories.jobs.list();
    let count = 0;
    for (const job of all) {
      if (isActive(job)) {
        // eslint-disable-next-line no-await-in-loop
        await this.deps.repositories.jobs.update(job.id, {
          status: 'failed',
          failureReason: 'interrupted before completion; safe to retry',
          updatedAt: new Date().toISOString(),
        });
        count += 1;
      }
    }
    return count;
  }

  private async setStatus(
    jobId: string,
    status: JobStatus,
    patch: Partial<AgentJob> = {},
  ): Promise<AgentJob> {
    const updated = await this.deps.repositories.jobs.update(jobId, {
      ...patch,
      status,
      updatedAt: new Date().toISOString(),
    });
    this.deps.onStatus?.(updated);
    return updated;
  }

  private async fail(jobId: string, reason: string): Promise<void> {
    const updated = await this.deps.repositories.jobs.update(jobId, {
      status: 'failed',
      failureReason: reason,
      updatedAt: new Date().toISOString(),
    });
    this.deps.onStatus?.(updated);
  }

  private async runPipeline(jobId: string, review: SubmittedReview, project: Project): Promise<void> {
    // 1. Create the generated branch directly in the repository (no worktree).
    await this.setStatus(jobId, 'preparing');
    const branch = generateBranchName(review.id);

    // Everything after the branch may be created runs inside the try so the
    // finally always returns the checkout to the base branch — even if branch
    // creation or the immediately-following persistence fails.
    try {
      await createReviewBranch(project.repoPath, branch, review.baseCommit);
      await this.deps.repositories.jobs.update(jobId, {
        branch,
        updatedAt: new Date().toISOString(),
      });
      const repositoryInfo = infoForProject(project, project.repoPath, review.baseCommit);

      // 2. Run the coding agent in the repository, on the generated branch.
      // We deliberately skip a pre-agent baseline on the happy path: gates would
      // otherwise run twice. If the post-change verify fails, we run the baseline
      // then (below) to attribute the failure.
      await this.setStatus(jobId, 'running-agent');
      const { system, user } = buildAgentPrompt({ review, verificationCommands: verificationCommands(project) });
      const logPath = this.deps.logsDir ? join(this.deps.logsDir, `${jobId}.log`) : undefined;
      if (this.deps.logsDir) await mkdir(this.deps.logsDir, { recursive: true });
      const agentResult = await this.deps.agent.run(
        { prompt: user, systemPrompt: system, cwd: project.repoPath },
        { logPath, timeoutMs: AGENT_TIMEOUT_MS },
      );
      await this.deps.repositories.jobs.update(jobId, { logPath, updatedAt: new Date().toISOString() });
      if (!agentResult.ok) {
        throw new JobError(agentFailureDetail(agentResult));
      }

      // 3. Require real changes before doing any further work.
      const changed = await changedFiles(project.repoPath);
      if (changed.length === 0) {
        throw new JobError('the agent made no changes; no pull request was created');
      }
      await assertSafeChangedFiles(project.repoPath, changed);
      await this.deps.repositories.jobs.update(jobId, {
        changedFiles: changed,
        updatedAt: new Date().toISOString(),
      });

      // 4. Verify BEFORE any commit/push. Failed verification blocks the PR.
      await this.setStatus(jobId, 'verifying');
      const verification = await verifyRepository(repositoryInfo, project.repoPath);
      await this.deps.repositories.jobs.update(jobId, {
        verification,
        updatedAt: new Date().toISOString(),
      });
      if (!verification.ok) {
        throw new JobError('verification failed on the change; no pull request was created');
      }

      // 5. Commit on the generated branch, push (never force), open a DRAFT PR.
      const commit = await commitAll(
        project.repoPath,
        `Pinpoint: apply visual feedback from ${review.reviewerName} (${review.id})`,
      );
      if (!commit.committed) {
        throw new JobError('no changes to commit; no pull request was created');
      }

      await this.setStatus(jobId, 'pushing');
      const pr = await openDraftPullRequest({
        cwd: project.repoPath,
        branch,
        baseBranch: review.baseBranch,
        title: `Apply visual feedback from ${review.reviewerName}`,
        body: prBody(review, changed, verification),
        repo: project.githubRepo,
        remote: 'origin',
      });

      // 6. Record the PR.
      await this.setStatus(jobId, 'pr-opened', { prUrl: pr.url });
    } finally {
      // Always return the developer's checkout to the review's base branch (e.g.
      // main), discarding any uncommitted edits — success or failure. Restoring
      // to the recorded base branch (not the branch that happened to be checked
      // out) avoids getting stranded on a stale generated branch from a prior job.
      // The generated branch and its commit remain locally and on the remote so
      // the pull request is unaffected.
      await restoreBranch(project.repoPath, review.baseBranch).catch(() => undefined);
    }
  }
}
