import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { entityId } from '../lib/ids';
import { buildAgentPrompt } from '../agents/prompt';
import {
  generateBranchName,
  currentBranch,
  createReviewBranch,
  changedFiles,
  commitAll,
  restoreBranch,
} from '../git/repo';
import { verifyRepository, type VerifyOptions } from '../git/verify';
import { assertSafeChangedFiles } from '../git/change-policy';
import { createDraftPullRequest, type DraftPrInput } from '../github/client';
import type { CodingAgent } from '../agents/types';
import type { Repositories } from '../storage/repositories';
import type {
  AgentJob,
  Command,
  JobStatus,
  Project,
  RepositoryInfo,
  SubmittedReview,
  VerificationResult,
} from '../domain/types';

/** Adapters over the git/verify/github modules, injectable for tests. */
export interface RepoAdapter {
  generateBranchName(seed: string): string;
  currentBranch(repoRoot: string): Promise<string>;
  createReviewBranch(repoRoot: string, branch: string, baseCommit: string): Promise<void>;
  changedFiles(repoRoot: string): Promise<string[]>;
  commitAll(repoRoot: string, message: string): Promise<{ committed: boolean; sha?: string }>;
  restoreBranch(repoRoot: string, branch: string): Promise<void>;
}

export interface VerifyAdapter {
  verifyRepository(info: RepositoryInfo, cwd: string, opts?: VerifyOptions): Promise<VerificationResult>;
}

export interface GithubAdapter {
  createDraftPullRequest(input: DraftPrInput): Promise<{ url: string; number: number }>;
}

export const realRepoAdapter: RepoAdapter = {
  generateBranchName,
  currentBranch,
  createReviewBranch,
  changedFiles,
  commitAll,
  restoreBranch,
};

export const realVerifyAdapter: VerifyAdapter = { verifyRepository };

export const realGithubAdapter: GithubAdapter = { createDraftPullRequest };

export interface OrchestratorDeps {
  repositories: Repositories;
  agent: CodingAgent;
  repo: RepoAdapter;
  verifier: VerifyAdapter;
  github: GithubAdapter;
  /** Directory for sanitized per-job agent logs. */
  logsDir?: string;
  /** Called on every persisted status change (including the initial queue). */
  onStatus?: (job: AgentJob) => void;
}

const TERMINAL: JobStatus[] = ['pr-opened', 'failed'];

function isActive(job: AgentJob): boolean {
  return !TERMINAL.includes(job.status);
}

/** Build a RepositoryInfo view from a project (used for verification gates). */
function infoForProject(project: Project, worktreePath: string, baseCommit: string): RepositoryInfo {
  // The job runs in the developer's actual repository, which already has its
  // dependencies installed. Skip the install gate (e.g. `npm ci`) — running it
  // here would wipe and reinstall the developer's node_modules unnecessarily.
  const commands = { ...project.commands };
  delete commands.install;
  return {
    root: worktreePath,
    clean: true,
    branch: project.baseBranch,
    commit: baseCommit,
    githubRepo: project.githubRepo,
    remoteUrl: project.remoteUrl,
    framework: project.framework,
    htmlEntry: project.htmlEntry,
    commands,
  };
}

/** Verification commands (arg arrays) surfaced to the agent, in run order. */
function verificationCommands(project: Project): string[][] {
  const order: (Command | undefined)[] = [
    project.commands.test,
    project.commands.lint,
    project.commands.typecheck,
    project.commands.build,
  ];
  return order.filter((c): c is Command => Boolean(c)).map((c) => [c.command, ...c.args]);
}

function prBody(review: SubmittedReview, changed: string[], verification: VerificationResult): string {
  const lines: string[] = [];
  lines.push(`## Visual feedback from ${review.reviewerName}`);
  lines.push('');
  lines.push(`Generated by Pinpoint from review \`${review.id}\` (base \`${review.baseCommit}\`).`);
  lines.push('');
  lines.push('### Feedback applied');
  review.annotations.forEach((a) => {
    const src = a.mapping.sourceFile ?? a.mapping.component ?? 'unresolved';
    lines.push(`${a.index}. **<${a.tag}>** — ${a.comment}  \n   _source: ${src}_`);
  });
  lines.push('');
  lines.push('### Files changed');
  changed.forEach((f) => lines.push(`- \`${f}\``));
  lines.push('');
  lines.push('### Verification');
  verification.checks
    .filter((c) => !c.skipped)
    .forEach((c) => lines.push(`- ${c.ok ? '✅' : '❌'} \`${c.command.join(' ')}\``));
  lines.push('');
  lines.push('---');
  lines.push('> Draft opened automatically. Review before merging. Pinpoint never merges or force-pushes.');
  return lines.join('\n');
}

/** A job failure carrying a human-readable reason for the dashboard. */
class JobError extends Error {}

/**
 * Persisted job state machine:
 *   queued → preparing → running-agent → verifying → pushing → pr-opened
 *                                                        ↘ failed (any stage)
 * State is persisted before and after every external operation so an
 * interrupted run can be recovered rather than silently rerun.
 */
export class Orchestrator {
  private readonly running = new Map<string, Promise<void>>();

  constructor(private readonly deps: OrchestratorDeps) {}

  async getJob(jobId: string): Promise<AgentJob | undefined> {
    return this.deps.repositories.jobs.get(jobId);
  }

  /** Await a started job's pipeline (test/shutdown helper). */
  async settle(jobId: string): Promise<void> {
    await this.running.get(jobId);
  }

  /** Await all in-flight pipelines. */
  async settleAll(): Promise<void> {
    await Promise.all([...this.running.values()]);
  }

  async startJobForReview(reviewId: string): Promise<AgentJob> {
    const review = await this.deps.repositories.reviews.get(reviewId);
    if (!review) throw new Error(`unknown review: ${reviewId}`);
    const project = await this.deps.repositories.projects.get(review.projectId);
    if (!project) throw new Error(`unknown project for review: ${reviewId}`);

    const all = await this.deps.repositories.jobs.list();
    const forReview = all.filter((j) => j.reviewId === reviewId);
    if (forReview.some(isActive)) {
      throw new Error('a job is already active for this review');
    }

    const now = new Date().toISOString();
    const job: AgentJob = {
      id: entityId('job'),
      reviewId,
      projectId: project.id,
      status: 'queued',
      attempts: forReview.length + 1,
      createdAt: now,
      updatedAt: now,
    };
    await this.deps.repositories.jobs.insert(job);
    this.deps.onStatus?.(job);

    const p = this.runPipeline(job.id, review, project).catch(async (err) => {
      await this.fail(job.id, err instanceof Error ? err.message : String(err));
    });
    this.running.set(job.id, p);
    return job;
  }

  /** Mark interrupted nonterminal jobs failed (recoverable) after a restart. */
  async recoverInterrupted(): Promise<number> {
    const all = await this.deps.repositories.jobs.list();
    let count = 0;
    for (const job of all) {
      if (isActive(job)) {
        // eslint-disable-next-line no-await-in-loop
        await this.deps.repositories.jobs.update(job.id, {
          status: 'failed',
          failureReason: 'interrupted before completion; safe to retry',
          updatedAt: new Date().toISOString(),
        });
        count += 1;
      }
    }
    return count;
  }

  private async setStatus(
    jobId: string,
    status: JobStatus,
    patch: Partial<AgentJob> = {},
  ): Promise<AgentJob> {
    const updated = await this.deps.repositories.jobs.update(jobId, {
      ...patch,
      status,
      updatedAt: new Date().toISOString(),
    });
    this.deps.onStatus?.(updated);
    return updated;
  }

  private async fail(jobId: string, reason: string): Promise<void> {
    const updated = await this.deps.repositories.jobs.update(jobId, {
      status: 'failed',
      failureReason: reason,
      updatedAt: new Date().toISOString(),
    });
    this.deps.onStatus?.(updated);
  }

  private async runPipeline(jobId: string, review: SubmittedReview, project: Project): Promise<void> {
    // 1. Create the generated branch directly in the repository (no worktree),
    //    remembering the developer's current branch so we can restore it after.
    await this.setStatus(jobId, 'preparing');
    const branch = this.deps.repo.generateBranchName(review.id);
    const originalBranch = await this.deps.repo.currentBranch(project.repoPath);
    await this.deps.repo.createReviewBranch(project.repoPath, branch, review.baseCommit);
    await this.deps.repositories.jobs.update(jobId, {
      branch,
      updatedAt: new Date().toISOString(),
    });

    try {
      // Establish a clean, reproducible baseline before the agent edits anything.
      // Pre-existing failures must not be blamed on client feedback.
      const repositoryInfo = infoForProject(project, project.repoPath, review.baseCommit);
      const baselineVerification = await this.deps.verifier.verifyRepository(
        repositoryInfo,
        project.repoPath,
      );
      await this.deps.repositories.jobs.update(jobId, {
        baselineVerification,
        updatedAt: new Date().toISOString(),
      });
      if (!baselineVerification.ok) {
        throw new JobError('repository baseline verification failed before agent execution');
      }

      // 2. Run the coding agent in the repository, on the generated branch.
      await this.setStatus(jobId, 'running-agent');
      const prompt = buildAgentPrompt({ review, verificationCommands: verificationCommands(project) });
      const logPath = this.deps.logsDir ? join(this.deps.logsDir, `${jobId}.log`) : undefined;
      if (this.deps.logsDir) await mkdir(this.deps.logsDir, { recursive: true });
      const agentResult = await this.deps.agent.run({ prompt, cwd: project.repoPath }, { logPath });
      await this.deps.repositories.jobs.update(jobId, { logPath, updatedAt: new Date().toISOString() });
      if (!agentResult.ok) {
        throw new JobError(
          agentResult.timedOut
            ? 'the coding agent timed out'
            : 'the coding agent did not complete successfully',
        );
      }

      // 3. Require real changes before doing any further work.
      const changed = await this.deps.repo.changedFiles(project.repoPath);
      if (changed.length === 0) {
        throw new JobError('the agent made no changes; no pull request was created');
      }
      await assertSafeChangedFiles(project.repoPath, changed);
      await this.deps.repositories.jobs.update(jobId, {
        changedFiles: changed,
        updatedAt: new Date().toISOString(),
      });

      // 4. Verify BEFORE any commit/push. Failed verification blocks the PR.
      await this.setStatus(jobId, 'verifying');
      const verification = await this.deps.verifier.verifyRepository(repositoryInfo, project.repoPath);
      await this.deps.repositories.jobs.update(jobId, {
        verification,
        updatedAt: new Date().toISOString(),
      });
      if (!verification.ok) {
        throw new JobError('verification failed; no pull request was created');
      }

      // 5. Commit on the generated branch, push (never force), open a DRAFT PR.
      const commit = await this.deps.repo.commitAll(
        project.repoPath,
        `Pinpoint: apply visual feedback from ${review.reviewerName} (${review.id})`,
      );
      if (!commit.committed) {
        throw new JobError('no changes to commit; no pull request was created');
      }

      await this.setStatus(jobId, 'pushing');
      const pr = await this.deps.github.createDraftPullRequest({
        cwd: project.repoPath,
        branch,
        baseBranch: review.baseBranch,
        title: `Apply visual feedback from ${review.reviewerName}`,
        body: prBody(review, changed, verification),
        repo: project.githubRepo,
        remote: 'origin',
      });

      // 6. Record the PR.
      await this.setStatus(jobId, 'pr-opened', { prUrl: pr.url, prNumber: pr.number });
    } finally {
      // Always return the developer's checkout to its original branch, discarding
      // any uncommitted edits. The generated branch (and its commit) remain both
      // locally and on the remote so the pull request is unaffected.
      await this.deps.repo.restoreBranch(project.repoPath, originalBranch).catch(() => undefined);
    }
  }
}
